export const projectTagPresets = [
  "Not started yet",
  "In progress",
  "Finished",
  "Looking for teammates",
  "Open to collaborators",
  "Software development",
  "Web development",
  "Mobile development",
  "UI design",
  "UX research",
  "Product design",
  "AI & machine learning",
  "Data science",
  "Cybersecurity",
  "Game development",
  "Business",
  "Entrepreneurship",
  "Marketing",
  "Finance",
  "Sustainability",
  "Education",
  "Research",
  "Social impact",
  "Hardware",
  "Project management",
] as const;

export type ProjectTagPreset = (typeof projectTagPresets)[number];
